### ISSUE TITLE
Fill install path in settings : menu start debugging does not work

### ISSUE THREAD

**Issue by GrandStrateguerre** [genius257/vscode-autoit3-debug#10]
Hello,

I entered the folder path but it does not work !?

![image](https://user-images.githubusercontent.com/86523070/226206842-b03e6138-988f-4ca1-b624-352934aaa603.png)

![image](https://user-images.githubusercontent.com/86523070/226206880-79f81427-0f60-45d0-939b-409073d3c538.png)

![image](https://user-images.githubusercontent.com/86523070/226206946-6b97bc8d-7bbc-4181-a5d4-d3cc19842f4e.png)

Best regards

**Comment by genius257** [comment]
Hi @GrandStrateguerre :smile: 
You need to add a AutoIt3 debug configuration to your workspace.
It is a bug that the message indicating no debugger is available when the configuration is missing however, i will look into that with a new issue tracking that specific issue :smile: 

For your solution:
![image](https://user-images.githubusercontent.com/7044927/226722680-ea39a846-eb29-48b0-b930-bb0b6efeb6d4.png)
![image](https://user-images.githubusercontent.com/7044927/226724508-df51d320-1fee-4bfb-8ef4-888720257207.png)

**Comment by genius257** [comment]
An update for this:
https://github.com/microsoft/vscode/issues/123881 helped me discover that i needed to fill out the language array in my debug extension configuration.

This will be fixed with a new extension version soon 😄

**Comment by genius257** [comment]
Should be fixed in release [v1.0.1](https://github.com/genius257/vscode-autoit3-debug/releases/tag/v1.0.1)
The new version is available on visual studio code marketplace
